/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsCountryRouteImport } from './routes/destinations.$country'
import { Route as DestinationsCountryIndexRouteImport } from './routes/destinations.$country.index'
import { Route as DestinationsCountryPlaceRouteImport } from './routes/destinations.$country.$place'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCountryRoute = DestinationsCountryRouteImport.update({
  id: '/destinations/$country',
  path: '/destinations/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsCountryIndexRoute =
  DestinationsCountryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DestinationsCountryRoute,
  } as any)
const DestinationsCountryPlaceRoute =
  DestinationsCountryPlaceRouteImport.update({
    id: '/$place',
    path: '/$place',
    getParentRoute: () => DestinationsCountryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$country/$place': typeof DestinationsCountryPlaceRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/$country/$place': typeof DestinationsCountryPlaceRoute
  '/destinations/$country': typeof DestinationsCountryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/destinations/$country': typeof DestinationsCountryRouteWithChildren
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/$country/$place': typeof DestinationsCountryPlaceRoute
  '/destinations/$country/': typeof DestinationsCountryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/packages'
    | '/services'
    | '/destinations/$country'
    | '/destinations/'
    | '/destinations/$country/$place'
    | '/destinations/$country/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/packages'
    | '/services'
    | '/destinations'
    | '/destinations/$country/$place'
    | '/destinations/$country'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/packages'
    | '/services'
    | '/destinations/$country'
    | '/destinations/'
    | '/destinations/$country/$place'
    | '/destinations/$country/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  ServicesRoute: typeof ServicesRoute
  DestinationsCountryRoute: typeof DestinationsCountryRouteWithChildren
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country': {
      id: '/destinations/$country'
      path: '/destinations/$country'
      fullPath: '/destinations/$country'
      preLoaderRoute: typeof DestinationsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$country/': {
      id: '/destinations/$country/'
      path: '/'
      fullPath: '/destinations/$country/'
      preLoaderRoute: typeof DestinationsCountryIndexRouteImport
      parentRoute: typeof DestinationsCountryRoute
    }
    '/destinations/$country/$place': {
      id: '/destinations/$country/$place'
      path: '/$place'
      fullPath: '/destinations/$country/$place'
      preLoaderRoute: typeof DestinationsCountryPlaceRouteImport
      parentRoute: typeof DestinationsCountryRoute
    }
  }
}

interface DestinationsCountryRouteChildren {
  DestinationsCountryPlaceRoute: typeof DestinationsCountryPlaceRoute
  DestinationsCountryIndexRoute: typeof DestinationsCountryIndexRoute
}

const DestinationsCountryRouteChildren: DestinationsCountryRouteChildren = {
  DestinationsCountryPlaceRoute: DestinationsCountryPlaceRoute,
  DestinationsCountryIndexRoute: DestinationsCountryIndexRoute,
}

const DestinationsCountryRouteWithChildren =
  DestinationsCountryRoute._addFileChildren(DestinationsCountryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  ServicesRoute: ServicesRoute,
  DestinationsCountryRoute: DestinationsCountryRouteWithChildren,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
